timeout: 5
default_entry: 2
remember_last_entry: yes

# CachyOS Limine theme
# Author: diegons490 (https://github.com/diegons490/cachyos-limine-theme)
#term_palette: 1e1e2e;f38ba8;a6e3a1;f9e2af;89b4fa;f5c2e7;94e2d5;cdd6f4
#term_palette_bright: 585b70;f38ba8;a6e3a1;f9e2af;89b4fa;f5c2e7;94e2d5;cdd6f4
#term_background: ffffffff
#term_foreground: cdd6f4
#term_background_bright: ffffffff
#term_foreground_bright: cdd6f4
#interface_branding:
#wallpaper: boot():/limine-splash.png

# CachyOS Cyberpunk Theme
# Neon Pink, Electric Blue, and Dark Background
term_palette: 000000;ff0055;00ff9f;f3e600;00b8ff;b908ff;00fff9;ffffff
term_palette_bright: 333333;ff0055;00ff9f;f3e600;00b8ff;b908ff;00fff9;ffffff
term_background: ffffffff
term_foreground: 00b8ff
term_background_bright: ffffffff
term_foreground_bright: 00b8ff
interface_branding: [ CYBERLINK :: CACHYOS ]
wallpaper: boot():/limine-splash.png

# Options for other systems and bootloaders can be added below. Just make sure to follow the syntax and structure as shown in the examples.

# Options

# /Options

/+Other systems and bootloaders
//Windows Boot Manager
    protocol: efi_chainload
    image_path: boot():/EFI/Microsoft/Boot/bootmgfw.efi
/EFI fallback
### This EFI entry is auto-generated by limine-entry-tool
comment: Default EFI loader
comment: order-priority=10 
protocol: efi
path: boot():/EFI/BOOT/BOOTX64.EFI


