Section "Files"
    ModulePath "/usr/lib/nvidia/xorg"
    ModulePath "/usr/lib/xorg/modules"
EndSection

Section "Device"
    Identifier "Nvidia Card"
    Driver "nvidia"
    Option "TripleBuffer" "True"
EndSection

Section "Screen"
    Identifier "Screen 0"
    Device "Nvidia Card"
    Option "ForceFullCompositionPipeline" "True"
EndSection
