#!/bin/sh

draw() {
  kitten icat --stdin no --transfer-mode memory \
    --place "${w}x${h}@${x}x${y}" "$1" </dev/null >/dev/tty
}

file="$1"
w="$2"
h="$3"
x="$4"
y="$5"

# Determine type for branching
mime=$(file -Lb --mime-type "$file")

case "$mime" in
    image/*)
        draw "$file"
        exit 1
        ;;
    application/pdf)
        CACHE=$(mktemp /tmp/lf-pdf.XXXXX)
        pdftoppm -png -f 1 -singlefile "$file" "$CACHE"
        draw "$CACHE.png"
        rm "$CACHE.png"
        exit 1
        ;;
esac

# Handle all other extensions
case "$file" in
    *.tgz|*.tar.gz) tar tzf "$file";;
    *.tar.bz2|*.tbz2) tar tjf "$file";;
    *.tar.txz|*.txz) xz --list "$file";;
    *.tar) tar tf "$file";;
    *.zip|*.jar|*.war|*.ear|*.oxt) unzip -l "$file";;
    *.rar) unrar l "$file";;
    *.7z) 7z l "$file";;
    *.[1-8]) man "$file" | col -b ;;
    *.o) nm "$file" ;;
    *.torrent) transmission-show "$file";;
    *.iso) iso-info --no-header -l "$file";;
    *odt,*.ods,*.odp,*.sxw) odt2txt "$file";;
    *.doc) catdoc "$file" ;;
    *.docx) docx2txt "$file" - ;;
    *.csv) cat "$file" | sed s/,/\\n/g ;;
    *.epub)
        CACHE=$(mktemp /tmp/thumbcache.XXXXX)
        epub-thumbnailer "$file" "$CACHE" 1024
        draw "$CACHE"
        rm "$CACHE"
        ;;
    *.wav|*.mp3|*.flac|*.m4a|*.wma|*.ape|*.ac3|*.og[agx]|*.spx|*.opus|*.as[fx]|*.flac) 
        exiftool "$file" ;;
    *.avi|*.mp4|*.wmv|*.dat|*.3gp|*.ogv|*.mkv|*.mpg|*.mpeg|*.vob|*.fl[icv]|*.m2v|*.mov|*.webm|*.ts|*.mts|*.m4v|*.r[am]|*.qt|*.divx)
        CACHE=$(mktemp /tmp/thumbcache.XXXXX.png)
        ffmpegthumbnailer -i "$file" -o "$CACHE" -s 0
        draw "$CACHE"
        rm "$CACHE"
        ;;
    *) 
        highlight --out-format ansi "$file" || cat "$file" ;;
esac

exit 1
